### ISSUE TITLE
Is this package working?

### ISSUE THREAD

**Issue by naxhh** [tellnes/bunyan-middleware#18]
I've made a very simple example and I'm failling to make it work.

```
"express": "4.14.0",
"bunyan": "1.8.12",
"bunyan-middleware": "0.8.0",
```

```
bunyan.createLogger({ name: 'my-app'})
app.use(bunyanMiddleware({ logger }))
```

When I run the app i get:

```

TypeError: Cannot read property 'res' of undefined
    at module.exports (/code/test/node_modules/bunyan-middleware/index.js:77:33)
    at Object.<anonymous> (/code/test/server/server.js:22:9)
    at Module._compile (module.js:573:30)
    at loader (/code/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/code/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

I can see the error is here:

```
, res: logger.serializers && logger.serializers.res || logger.constructor.stdSerializers.res
```

And from what I see my logger has:

```
logger.default.serializer: null
```

So the bunyan-middleware package is not counting on that `default` key.
I'm doing something wrong? Is `bunyan-middleware` not expected to work with this version of bunyan?

**Comment by naxhh** [comment]
Nevermind, This has nothing to do with bunyan or this package but my inability to mix imports and requires ^^

Have a nice day.
